export interface Recipe {
  id: number;
  title: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  rating: number;
  image: string;
  tags: string[];
  recipeUrl: string;
  description: string;
  mealType?: 'breakfast' | 'lunch' | 'dinner' | 'snacks';
}

export const recipeDatabase: Recipe[] = [
  {
    id: 1,
    title: 'Mediterranean Quinoa Salad',
    calories: 320,
    protein: 12,
    carbs: 45,
    fat: 10,
    prepTime: 15,
    difficulty: 'Easy',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    tags: ['Vegetarian', 'High Protein', 'Gluten-Free'],
    recipeUrl: 'https://www.allrecipes.com/recipe/229156/zesty-quinoa-salad/',
    description: 'A fresh and healthy quinoa salad with Mediterranean flavors',
    mealType: 'lunch',
  },
  {
    id: 2,
    title: 'Grilled Salmon with Vegetables',
    calories: 425,
    protein: 38,
    carbs: 22,
    fat: 20,
    prepTime: 25,
    difficulty: 'Medium',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    tags: ['High Protein', 'Omega-3', 'Low Carb'],
    recipeUrl: 'https://www.allrecipes.com/recipe/12720/grilled-salmon-i/',
    description: 'Perfectly grilled salmon with roasted seasonal vegetables',
    mealType: 'dinner',
  },
  {
    id: 3,
    title: 'Green Smoothie Bowl',
    calories: 280,
    protein: 8,
    carbs: 52,
    fat: 6,
    prepTime: 10,
    difficulty: 'Easy',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    tags: ['Vegan', 'Antioxidants', 'Breakfast'],
    recipeUrl: 'https://www.allrecipes.com/recipe/245425/green-smoothie-bowl/',
    description: 'Nutrient-packed smoothie bowl with fresh fruits and toppings',
    mealType: 'breakfast',
  },
  {
    id: 4,
    title: 'Chicken Stir-Fry',
    calories: 380,
    protein: 32,
    carbs: 35,
    fat: 12,
    prepTime: 20,
    difficulty: 'Easy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    tags: ['High Protein', 'Quick', 'Asian'],
    recipeUrl: 'https://www.allrecipes.com/recipe/223382/chicken-stir-fry/',
    description: 'Quick and easy chicken stir-fry with colorful vegetables',
    mealType: 'dinner',
  },
  {
    id: 5,
    title: 'Avocado Toast',
    calories: 290,
    protein: 10,
    carbs: 28,
    fat: 16,
    prepTime: 5,
    difficulty: 'Easy',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
    tags: ['Vegetarian', 'Quick', 'Healthy Fats'],
    recipeUrl: 'https://www.allrecipes.com/recipe/270775/avocado-toast/',
    description: 'Classic avocado toast with a perfect blend of flavors',
    mealType: 'breakfast',
  },
  {
    id: 6,
    title: 'Greek Yogurt Parfait',
    calories: 250,
    protein: 18,
    carbs: 38,
    fat: 4,
    prepTime: 5,
    difficulty: 'Easy',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800',
    tags: ['High Protein', 'Breakfast', 'Quick'],
    recipeUrl: 'https://www.allrecipes.com/recipe/240673/yogurt-parfait/',
    description: 'Layered yogurt parfait with fresh berries and granola',
    mealType: 'breakfast',
  },
  {
    id: 7,
    title: 'Lentil Soup',
    calories: 310,
    protein: 18,
    carbs: 48,
    fat: 6,
    prepTime: 45,
    difficulty: 'Medium',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    tags: ['Vegan', 'High Fiber', 'Comfort Food'],
    recipeUrl: 'https://www.allrecipes.com/recipe/13978/lentil-soup/',
    description: 'Hearty and nutritious lentil soup packed with vegetables',
    mealType: 'lunch',
  },
  {
    id: 8,
    title: 'Protein Pancakes',
    calories: 340,
    protein: 24,
    carbs: 42,
    fat: 8,
    prepTime: 15,
    difficulty: 'Easy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    tags: ['High Protein', 'Breakfast', 'Fitness'],
    recipeUrl: 'https://www.allrecipes.com/recipe/241059/protein-pancakes/',
    description: 'Fluffy protein-packed pancakes perfect for post-workout',
    mealType: 'breakfast',
  },
  {
    id: 9,
    title: 'Caprese Salad',
    calories: 220,
    protein: 14,
    carbs: 8,
    fat: 16,
    prepTime: 10,
    difficulty: 'Easy',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800',
    tags: ['Vegetarian', 'Low Carb', 'Italian'],
    recipeUrl: 'https://www.allrecipes.com/recipe/228126/insalata-caprese/',
    description: 'Classic Italian salad with fresh mozzarella and tomatoes',
    mealType: 'lunch',
  },
  {
    id: 10,
    title: 'Beef Tacos',
    calories: 420,
    protein: 28,
    carbs: 38,
    fat: 18,
    prepTime: 20,
    difficulty: 'Easy',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    tags: ['High Protein', 'Mexican', 'Family Friendly'],
    recipeUrl: 'https://www.allrecipes.com/recipe/70935/basic-taco-meat/',
    description: 'Delicious beef tacos with fresh toppings',
    mealType: 'dinner',
  },
  {
    id: 11,
    title: 'Buddha Bowl',
    calories: 380,
    protein: 16,
    carbs: 54,
    fat: 12,
    prepTime: 25,
    difficulty: 'Medium',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    tags: ['Vegan', 'Balanced', 'Nutrient Dense'],
    recipeUrl: 'https://www.allrecipes.com/recipe/260467/vegan-buddha-bowl/',
    description: 'Colorful and balanced bowl with grains, veggies, and protein',
    mealType: 'lunch',
  },
  {
    id: 12,
    title: 'Oatmeal with Berries',
    calories: 260,
    protein: 10,
    carbs: 48,
    fat: 5,
    prepTime: 10,
    difficulty: 'Easy',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800',
    tags: ['Vegetarian', 'High Fiber', 'Heart Healthy'],
    recipeUrl: 'https://www.allrecipes.com/recipe/142931/basic-oatmeal/',
    description: 'Warm oatmeal topped with fresh berries and honey',
    mealType: 'breakfast',
  },
  {
    id: 13,
    title: 'Hummus & Veggie Wrap',
    calories: 310,
    protein: 12,
    carbs: 42,
    fat: 11,
    prepTime: 10,
    difficulty: 'Easy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800',
    tags: ['Vegan', 'Quick', 'Portable'],
    recipeUrl: 'https://www.allrecipes.com/recipe/221782/hummus-veggie-wrap/',
    description: 'Fresh veggie wrap with creamy hummus',
    mealType: 'lunch',
  },
  {
    id: 14,
    title: 'Baked Chicken Breast',
    calories: 320,
    protein: 42,
    carbs: 2,
    fat: 14,
    prepTime: 30,
    difficulty: 'Easy',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    tags: ['High Protein', 'Low Carb', 'Keto Friendly'],
    recipeUrl: 'https://www.allrecipes.com/recipe/240208/perfectly-baked-chicken-breast/',
    description: 'Juicy baked chicken breast with herbs',
    mealType: 'dinner',
  },
  {
    id: 15,
    title: 'Energy Balls',
    calories: 180,
    protein: 6,
    carbs: 22,
    fat: 8,
    prepTime: 15,
    difficulty: 'Easy',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1593560704563-f176a2eb61db?w=800',
    tags: ['Snack', 'No Bake', 'Energy Boost'],
    recipeUrl: 'https://www.allrecipes.com/recipe/240417/no-bake-energy-balls/',
    description: 'Quick energy balls with oats, dates, and nuts',
    mealType: 'snacks',
  },
  {
    id: 16,
    title: 'Vegetable Curry',
    calories: 340,
    protein: 10,
    carbs: 52,
    fat: 12,
    prepTime: 35,
    difficulty: 'Medium',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    tags: ['Vegan', 'Indian', 'Spicy'],
    recipeUrl: 'https://www.allrecipes.com/recipe/16641/vegetable-curry/',
    description: 'Aromatic vegetable curry with coconut milk',
    mealType: 'dinner',
  },
  {
    id: 17,
    title: 'Chia Pudding',
    calories: 220,
    protein: 8,
    carbs: 28,
    fat: 10,
    prepTime: 5,
    difficulty: 'Easy',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800',
    tags: ['Vegan', 'Overnight', 'Omega-3'],
    recipeUrl: 'https://www.allrecipes.com/recipe/234307/creamy-chia-seed-pudding/',
    description: 'Creamy chia pudding with almond milk',
    mealType: 'breakfast',
  },
  {
    id: 18,
    title: 'Turkey Sandwich',
    calories: 360,
    protein: 28,
    carbs: 42,
    fat: 10,
    prepTime: 10,
    difficulty: 'Easy',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1619894989876-f8f2e0b0b5f4?w=800',
    tags: ['High Protein', 'Quick', 'Lunch'],
    recipeUrl: 'https://www.allrecipes.com/recipe/49943/the-best-turkey-sandwich/',
    description: 'Classic turkey sandwich with fresh vegetables',
    mealType: 'lunch',
  },
];

export function searchRecipes(query: string): Recipe[] {
  const lowerQuery = query.toLowerCase();
  return recipeDatabase.filter(recipe => 
    recipe.title.toLowerCase().includes(lowerQuery) ||
    recipe.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    recipe.description.toLowerCase().includes(lowerQuery)
  );
}

export function getRecipesByMealType(mealType: 'breakfast' | 'lunch' | 'dinner' | 'snacks'): Recipe[] {
  return recipeDatabase.filter(recipe => recipe.mealType === mealType);
}

export function getRecipeById(id: number): Recipe | undefined {
  return recipeDatabase.find(recipe => recipe.id === id);
}
